// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/lixin9311/vac-bot/ent/migrate"

	"github.com/lixin9311/vac-bot/ent/vacdepartment"
	"github.com/lixin9311/vac-bot/ent/vacuser"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// VacDepartment is the client for interacting with the VacDepartment builders.
	VacDepartment *VacDepartmentClient
	// VacUser is the client for interacting with the VacUser builders.
	VacUser *VacUserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.VacDepartment = NewVacDepartmentClient(c.config)
	c.VacUser = NewVacUserClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		VacDepartment: NewVacDepartmentClient(cfg),
		VacUser:       NewVacUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:        cfg,
		VacDepartment: NewVacDepartmentClient(cfg),
		VacUser:       NewVacUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		VacDepartment.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.VacDepartment.Use(hooks...)
	c.VacUser.Use(hooks...)
}

// VacDepartmentClient is a client for the VacDepartment schema.
type VacDepartmentClient struct {
	config
}

// NewVacDepartmentClient returns a client for the VacDepartment from the given config.
func NewVacDepartmentClient(c config) *VacDepartmentClient {
	return &VacDepartmentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `vacdepartment.Hooks(f(g(h())))`.
func (c *VacDepartmentClient) Use(hooks ...Hook) {
	c.hooks.VacDepartment = append(c.hooks.VacDepartment, hooks...)
}

// Create returns a create builder for VacDepartment.
func (c *VacDepartmentClient) Create() *VacDepartmentCreate {
	mutation := newVacDepartmentMutation(c.config, OpCreate)
	return &VacDepartmentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of VacDepartment entities.
func (c *VacDepartmentClient) CreateBulk(builders ...*VacDepartmentCreate) *VacDepartmentCreateBulk {
	return &VacDepartmentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for VacDepartment.
func (c *VacDepartmentClient) Update() *VacDepartmentUpdate {
	mutation := newVacDepartmentMutation(c.config, OpUpdate)
	return &VacDepartmentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *VacDepartmentClient) UpdateOne(vd *VacDepartment) *VacDepartmentUpdateOne {
	mutation := newVacDepartmentMutation(c.config, OpUpdateOne, withVacDepartment(vd))
	return &VacDepartmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *VacDepartmentClient) UpdateOneID(id int) *VacDepartmentUpdateOne {
	mutation := newVacDepartmentMutation(c.config, OpUpdateOne, withVacDepartmentID(id))
	return &VacDepartmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for VacDepartment.
func (c *VacDepartmentClient) Delete() *VacDepartmentDelete {
	mutation := newVacDepartmentMutation(c.config, OpDelete)
	return &VacDepartmentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *VacDepartmentClient) DeleteOne(vd *VacDepartment) *VacDepartmentDeleteOne {
	return c.DeleteOneID(vd.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *VacDepartmentClient) DeleteOneID(id int) *VacDepartmentDeleteOne {
	builder := c.Delete().Where(vacdepartment.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &VacDepartmentDeleteOne{builder}
}

// Query returns a query builder for VacDepartment.
func (c *VacDepartmentClient) Query() *VacDepartmentQuery {
	return &VacDepartmentQuery{
		config: c.config,
	}
}

// Get returns a VacDepartment entity by its id.
func (c *VacDepartmentClient) Get(ctx context.Context, id int) (*VacDepartment, error) {
	return c.Query().Where(vacdepartment.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *VacDepartmentClient) GetX(ctx context.Context, id int) *VacDepartment {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *VacDepartmentClient) Hooks() []Hook {
	return c.hooks.VacDepartment
}

// VacUserClient is a client for the VacUser schema.
type VacUserClient struct {
	config
}

// NewVacUserClient returns a client for the VacUser from the given config.
func NewVacUserClient(c config) *VacUserClient {
	return &VacUserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `vacuser.Hooks(f(g(h())))`.
func (c *VacUserClient) Use(hooks ...Hook) {
	c.hooks.VacUser = append(c.hooks.VacUser, hooks...)
}

// Create returns a create builder for VacUser.
func (c *VacUserClient) Create() *VacUserCreate {
	mutation := newVacUserMutation(c.config, OpCreate)
	return &VacUserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of VacUser entities.
func (c *VacUserClient) CreateBulk(builders ...*VacUserCreate) *VacUserCreateBulk {
	return &VacUserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for VacUser.
func (c *VacUserClient) Update() *VacUserUpdate {
	mutation := newVacUserMutation(c.config, OpUpdate)
	return &VacUserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *VacUserClient) UpdateOne(vu *VacUser) *VacUserUpdateOne {
	mutation := newVacUserMutation(c.config, OpUpdateOne, withVacUser(vu))
	return &VacUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *VacUserClient) UpdateOneID(id int) *VacUserUpdateOne {
	mutation := newVacUserMutation(c.config, OpUpdateOne, withVacUserID(id))
	return &VacUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for VacUser.
func (c *VacUserClient) Delete() *VacUserDelete {
	mutation := newVacUserMutation(c.config, OpDelete)
	return &VacUserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *VacUserClient) DeleteOne(vu *VacUser) *VacUserDeleteOne {
	return c.DeleteOneID(vu.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *VacUserClient) DeleteOneID(id int) *VacUserDeleteOne {
	builder := c.Delete().Where(vacuser.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &VacUserDeleteOne{builder}
}

// Query returns a query builder for VacUser.
func (c *VacUserClient) Query() *VacUserQuery {
	return &VacUserQuery{
		config: c.config,
	}
}

// Get returns a VacUser entity by its id.
func (c *VacUserClient) Get(ctx context.Context, id int) (*VacUser, error) {
	return c.Query().Where(vacuser.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *VacUserClient) GetX(ctx context.Context, id int) *VacUser {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *VacUserClient) Hooks() []Hook {
	return c.hooks.VacUser
}
