// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/lixin9311/vac-bot/ent/schema"
	"github.com/lixin9311/vac-bot/ent/vacdepartment"
	"github.com/lixin9311/vac-bot/ent/vacuser"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	vacdepartmentMixin := schema.VacDepartment{}.Mixin()
	vacdepartmentMixinFields0 := vacdepartmentMixin[0].Fields()
	_ = vacdepartmentMixinFields0
	vacdepartmentFields := schema.VacDepartment{}.Fields()
	_ = vacdepartmentFields
	// vacdepartmentDescCreatedAt is the schema descriptor for created_at field.
	vacdepartmentDescCreatedAt := vacdepartmentMixinFields0[0].Descriptor()
	// vacdepartment.DefaultCreatedAt holds the default value on creation for the created_at field.
	vacdepartment.DefaultCreatedAt = vacdepartmentDescCreatedAt.Default.(func() time.Time)
	// vacdepartmentDescUpdatedAt is the schema descriptor for updated_at field.
	vacdepartmentDescUpdatedAt := vacdepartmentMixinFields0[1].Descriptor()
	// vacdepartment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vacdepartment.DefaultUpdatedAt = vacdepartmentDescUpdatedAt.Default.(func() time.Time)
	// vacdepartment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vacdepartment.UpdateDefaultUpdatedAt = vacdepartmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	vacuserMixin := schema.VacUser{}.Mixin()
	vacuserMixinFields0 := vacuserMixin[0].Fields()
	_ = vacuserMixinFields0
	vacuserFields := schema.VacUser{}.Fields()
	_ = vacuserFields
	// vacuserDescCreatedAt is the schema descriptor for created_at field.
	vacuserDescCreatedAt := vacuserMixinFields0[0].Descriptor()
	// vacuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	vacuser.DefaultCreatedAt = vacuserDescCreatedAt.Default.(func() time.Time)
	// vacuserDescUpdatedAt is the schema descriptor for updated_at field.
	vacuserDescUpdatedAt := vacuserMixinFields0[1].Descriptor()
	// vacuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vacuser.DefaultUpdatedAt = vacuserDescUpdatedAt.Default.(func() time.Time)
	// vacuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vacuser.UpdateDefaultUpdatedAt = vacuserDescUpdatedAt.UpdateDefault.(func() time.Time)
}
