// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lixin9311/vac-bot/ent/predicate"
	"github.com/lixin9311/vac-bot/ent/vacdepartment"
)

// VacDepartmentQuery is the builder for querying VacDepartment entities.
type VacDepartmentQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.VacDepartment
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VacDepartmentQuery builder.
func (vdq *VacDepartmentQuery) Where(ps ...predicate.VacDepartment) *VacDepartmentQuery {
	vdq.predicates = append(vdq.predicates, ps...)
	return vdq
}

// Limit adds a limit step to the query.
func (vdq *VacDepartmentQuery) Limit(limit int) *VacDepartmentQuery {
	vdq.limit = &limit
	return vdq
}

// Offset adds an offset step to the query.
func (vdq *VacDepartmentQuery) Offset(offset int) *VacDepartmentQuery {
	vdq.offset = &offset
	return vdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vdq *VacDepartmentQuery) Unique(unique bool) *VacDepartmentQuery {
	vdq.unique = &unique
	return vdq
}

// Order adds an order step to the query.
func (vdq *VacDepartmentQuery) Order(o ...OrderFunc) *VacDepartmentQuery {
	vdq.order = append(vdq.order, o...)
	return vdq
}

// First returns the first VacDepartment entity from the query.
// Returns a *NotFoundError when no VacDepartment was found.
func (vdq *VacDepartmentQuery) First(ctx context.Context) (*VacDepartment, error) {
	nodes, err := vdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{vacdepartment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vdq *VacDepartmentQuery) FirstX(ctx context.Context) *VacDepartment {
	node, err := vdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VacDepartment ID from the query.
// Returns a *NotFoundError when no VacDepartment ID was found.
func (vdq *VacDepartmentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{vacdepartment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vdq *VacDepartmentQuery) FirstIDX(ctx context.Context) int {
	id, err := vdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VacDepartment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one VacDepartment entity is not found.
// Returns a *NotFoundError when no VacDepartment entities are found.
func (vdq *VacDepartmentQuery) Only(ctx context.Context) (*VacDepartment, error) {
	nodes, err := vdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{vacdepartment.Label}
	default:
		return nil, &NotSingularError{vacdepartment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vdq *VacDepartmentQuery) OnlyX(ctx context.Context) *VacDepartment {
	node, err := vdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VacDepartment ID in the query.
// Returns a *NotSingularError when exactly one VacDepartment ID is not found.
// Returns a *NotFoundError when no entities are found.
func (vdq *VacDepartmentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{vacdepartment.Label}
	default:
		err = &NotSingularError{vacdepartment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vdq *VacDepartmentQuery) OnlyIDX(ctx context.Context) int {
	id, err := vdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VacDepartments.
func (vdq *VacDepartmentQuery) All(ctx context.Context) ([]*VacDepartment, error) {
	if err := vdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return vdq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (vdq *VacDepartmentQuery) AllX(ctx context.Context) []*VacDepartment {
	nodes, err := vdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VacDepartment IDs.
func (vdq *VacDepartmentQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := vdq.Select(vacdepartment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vdq *VacDepartmentQuery) IDsX(ctx context.Context) []int {
	ids, err := vdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vdq *VacDepartmentQuery) Count(ctx context.Context) (int, error) {
	if err := vdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return vdq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (vdq *VacDepartmentQuery) CountX(ctx context.Context) int {
	count, err := vdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vdq *VacDepartmentQuery) Exist(ctx context.Context) (bool, error) {
	if err := vdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return vdq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (vdq *VacDepartmentQuery) ExistX(ctx context.Context) bool {
	exist, err := vdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VacDepartmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vdq *VacDepartmentQuery) Clone() *VacDepartmentQuery {
	if vdq == nil {
		return nil
	}
	return &VacDepartmentQuery{
		config:     vdq.config,
		limit:      vdq.limit,
		offset:     vdq.offset,
		order:      append([]OrderFunc{}, vdq.order...),
		predicates: append([]predicate.VacDepartment{}, vdq.predicates...),
		// clone intermediate query.
		sql:  vdq.sql.Clone(),
		path: vdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VacDepartment.Query().
//		GroupBy(vacdepartment.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (vdq *VacDepartmentQuery) GroupBy(field string, fields ...string) *VacDepartmentGroupBy {
	group := &VacDepartmentGroupBy{config: vdq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := vdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return vdq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.VacDepartment.Query().
//		Select(vacdepartment.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (vdq *VacDepartmentQuery) Select(field string, fields ...string) *VacDepartmentSelect {
	vdq.fields = append([]string{field}, fields...)
	return &VacDepartmentSelect{VacDepartmentQuery: vdq}
}

func (vdq *VacDepartmentQuery) prepareQuery(ctx context.Context) error {
	for _, f := range vdq.fields {
		if !vacdepartment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vdq.path != nil {
		prev, err := vdq.path(ctx)
		if err != nil {
			return err
		}
		vdq.sql = prev
	}
	return nil
}

func (vdq *VacDepartmentQuery) sqlAll(ctx context.Context) ([]*VacDepartment, error) {
	var (
		nodes = []*VacDepartment{}
		_spec = vdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &VacDepartment{config: vdq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, vdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (vdq *VacDepartmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vdq.querySpec()
	return sqlgraph.CountNodes(ctx, vdq.driver, _spec)
}

func (vdq *VacDepartmentQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := vdq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (vdq *VacDepartmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   vacdepartment.Table,
			Columns: vacdepartment.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: vacdepartment.FieldID,
			},
		},
		From:   vdq.sql,
		Unique: true,
	}
	if unique := vdq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := vdq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vacdepartment.FieldID)
		for i := range fields {
			if fields[i] != vacdepartment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vdq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vdq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vdq *VacDepartmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vdq.driver.Dialect())
	t1 := builder.Table(vacdepartment.Table)
	selector := builder.Select(t1.Columns(vacdepartment.Columns...)...).From(t1)
	if vdq.sql != nil {
		selector = vdq.sql
		selector.Select(selector.Columns(vacdepartment.Columns...)...)
	}
	for _, p := range vdq.predicates {
		p(selector)
	}
	for _, p := range vdq.order {
		p(selector)
	}
	if offset := vdq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vdq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VacDepartmentGroupBy is the group-by builder for VacDepartment entities.
type VacDepartmentGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vdgb *VacDepartmentGroupBy) Aggregate(fns ...AggregateFunc) *VacDepartmentGroupBy {
	vdgb.fns = append(vdgb.fns, fns...)
	return vdgb
}

// Scan applies the group-by query and scans the result into the given value.
func (vdgb *VacDepartmentGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := vdgb.path(ctx)
	if err != nil {
		return err
	}
	vdgb.sql = query
	return vdgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (vdgb *VacDepartmentGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := vdgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (vdgb *VacDepartmentGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(vdgb.fields) > 1 {
		return nil, errors.New("ent: VacDepartmentGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := vdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (vdgb *VacDepartmentGroupBy) StringsX(ctx context.Context) []string {
	v, err := vdgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vdgb *VacDepartmentGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = vdgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vacdepartment.Label}
	default:
		err = fmt.Errorf("ent: VacDepartmentGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (vdgb *VacDepartmentGroupBy) StringX(ctx context.Context) string {
	v, err := vdgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (vdgb *VacDepartmentGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(vdgb.fields) > 1 {
		return nil, errors.New("ent: VacDepartmentGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := vdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (vdgb *VacDepartmentGroupBy) IntsX(ctx context.Context) []int {
	v, err := vdgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vdgb *VacDepartmentGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = vdgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vacdepartment.Label}
	default:
		err = fmt.Errorf("ent: VacDepartmentGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (vdgb *VacDepartmentGroupBy) IntX(ctx context.Context) int {
	v, err := vdgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (vdgb *VacDepartmentGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(vdgb.fields) > 1 {
		return nil, errors.New("ent: VacDepartmentGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := vdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (vdgb *VacDepartmentGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := vdgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vdgb *VacDepartmentGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = vdgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vacdepartment.Label}
	default:
		err = fmt.Errorf("ent: VacDepartmentGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (vdgb *VacDepartmentGroupBy) Float64X(ctx context.Context) float64 {
	v, err := vdgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (vdgb *VacDepartmentGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(vdgb.fields) > 1 {
		return nil, errors.New("ent: VacDepartmentGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := vdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (vdgb *VacDepartmentGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := vdgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vdgb *VacDepartmentGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = vdgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vacdepartment.Label}
	default:
		err = fmt.Errorf("ent: VacDepartmentGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (vdgb *VacDepartmentGroupBy) BoolX(ctx context.Context) bool {
	v, err := vdgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (vdgb *VacDepartmentGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range vdgb.fields {
		if !vacdepartment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := vdgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vdgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (vdgb *VacDepartmentGroupBy) sqlQuery() *sql.Selector {
	selector := vdgb.sql
	columns := make([]string, 0, len(vdgb.fields)+len(vdgb.fns))
	columns = append(columns, vdgb.fields...)
	for _, fn := range vdgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(vdgb.fields...)
}

// VacDepartmentSelect is the builder for selecting fields of VacDepartment entities.
type VacDepartmentSelect struct {
	*VacDepartmentQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (vds *VacDepartmentSelect) Scan(ctx context.Context, v interface{}) error {
	if err := vds.prepareQuery(ctx); err != nil {
		return err
	}
	vds.sql = vds.VacDepartmentQuery.sqlQuery(ctx)
	return vds.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (vds *VacDepartmentSelect) ScanX(ctx context.Context, v interface{}) {
	if err := vds.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (vds *VacDepartmentSelect) Strings(ctx context.Context) ([]string, error) {
	if len(vds.fields) > 1 {
		return nil, errors.New("ent: VacDepartmentSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := vds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (vds *VacDepartmentSelect) StringsX(ctx context.Context) []string {
	v, err := vds.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (vds *VacDepartmentSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = vds.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vacdepartment.Label}
	default:
		err = fmt.Errorf("ent: VacDepartmentSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (vds *VacDepartmentSelect) StringX(ctx context.Context) string {
	v, err := vds.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (vds *VacDepartmentSelect) Ints(ctx context.Context) ([]int, error) {
	if len(vds.fields) > 1 {
		return nil, errors.New("ent: VacDepartmentSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := vds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (vds *VacDepartmentSelect) IntsX(ctx context.Context) []int {
	v, err := vds.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (vds *VacDepartmentSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = vds.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vacdepartment.Label}
	default:
		err = fmt.Errorf("ent: VacDepartmentSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (vds *VacDepartmentSelect) IntX(ctx context.Context) int {
	v, err := vds.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (vds *VacDepartmentSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(vds.fields) > 1 {
		return nil, errors.New("ent: VacDepartmentSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := vds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (vds *VacDepartmentSelect) Float64sX(ctx context.Context) []float64 {
	v, err := vds.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (vds *VacDepartmentSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = vds.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vacdepartment.Label}
	default:
		err = fmt.Errorf("ent: VacDepartmentSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (vds *VacDepartmentSelect) Float64X(ctx context.Context) float64 {
	v, err := vds.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (vds *VacDepartmentSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(vds.fields) > 1 {
		return nil, errors.New("ent: VacDepartmentSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := vds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (vds *VacDepartmentSelect) BoolsX(ctx context.Context) []bool {
	v, err := vds.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (vds *VacDepartmentSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = vds.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vacdepartment.Label}
	default:
		err = fmt.Errorf("ent: VacDepartmentSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (vds *VacDepartmentSelect) BoolX(ctx context.Context) bool {
	v, err := vds.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (vds *VacDepartmentSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := vds.sqlQuery().Query()
	if err := vds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (vds *VacDepartmentSelect) sqlQuery() sql.Querier {
	selector := vds.sql
	selector.Select(selector.Columns(vds.fields...)...)
	return selector
}
