// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lixin9311/vac-bot/ent/predicate"
	"github.com/lixin9311/vac-bot/ent/vacdepartment"
)

// VacDepartmentDelete is the builder for deleting a VacDepartment entity.
type VacDepartmentDelete struct {
	config
	hooks    []Hook
	mutation *VacDepartmentMutation
}

// Where adds a new predicate to the VacDepartmentDelete builder.
func (vdd *VacDepartmentDelete) Where(ps ...predicate.VacDepartment) *VacDepartmentDelete {
	vdd.mutation.predicates = append(vdd.mutation.predicates, ps...)
	return vdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vdd *VacDepartmentDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(vdd.hooks) == 0 {
		affected, err = vdd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VacDepartmentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			vdd.mutation = mutation
			affected, err = vdd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(vdd.hooks) - 1; i >= 0; i-- {
			mut = vdd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vdd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (vdd *VacDepartmentDelete) ExecX(ctx context.Context) int {
	n, err := vdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vdd *VacDepartmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: vacdepartment.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: vacdepartment.FieldID,
			},
		},
	}
	if ps := vdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, vdd.driver, _spec)
}

// VacDepartmentDeleteOne is the builder for deleting a single VacDepartment entity.
type VacDepartmentDeleteOne struct {
	vdd *VacDepartmentDelete
}

// Exec executes the deletion query.
func (vddo *VacDepartmentDeleteOne) Exec(ctx context.Context) error {
	n, err := vddo.vdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{vacdepartment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vddo *VacDepartmentDeleteOne) ExecX(ctx context.Context) {
	vddo.vdd.ExecX(ctx)
}
