// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// VacDepartment is the predicate function for vacdepartment builders.
type VacDepartment func(*sql.Selector)

// VacUser is the predicate function for vacuser builders.
type VacUser func(*sql.Selector)
